name: Build nexo SDK

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version (np. 50_0_2)'
        required: true
        type: string

jobs:
  build_and_push-windows:
    runs-on: windows-latest
    if: ${{ inputs.tag }} 
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . -t nexo-sdk -f src/${{ inputs.tag }}/windows/Dockerfile

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker image
        run: docker tag nexo-sdk ghcr.io/${{ github.repository_owner }}/nexo-sdk:${{ inputs.tag }}_win

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/nexo-sdk:${{ inputs.tag }}_win
  

  build_and_push-linux:
    runs-on: ubuntu-latest
    if: ${{ inputs.tag }} 
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . -t nexo-sdk -f src/${{ inputs.tag }}/linux/Dockerfile

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker image
        run: docker tag nexo-sdk ghcr.io/${{ github.repository_owner }}/nexo-sdk:${{ inputs.tag }}_linux

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/nexo-sdk:${{ inputs.tag }}_linux
